platform:
  - x86
  - x64
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
    # Output useful info for debugging.
  - node --version
  - npm --version
  # Typical npm stuff.
  - npm install
  - npm test
# Post-install test scripts.
# test_script:
#   # Output useful info for debugging.
#   - node --version
#   - npm --version
build: off
cache: node_modules
environment:
  matrix:
    - nodejs_version: "9.3.0"   # same results as 9.0, 9.1, 9.2
    - nodejs_version: "8.9.4"   # same results as 8.7, 8.8, 8.9
    - nodejs_version: "8.6.0"   # same results as 8.3, 8.4, 8.5
    - nodejs_version: "8.2.1"   # same results as 8.0, 8.1, 8.2
    - nodejs_version: "7.10.1"  # same results as 7.6, 7.7, 7.8, 7.9, 7.10
    - nodejs_version: "7.5.0"   # same results as 7.1, 7.2, 7.3, 7.4
    - nodejs_version: "6.12.3"  # same results as 6.5, 6.6, 6.7, 6.8, 6.9, 6.10, 6.11, 6.12
    - nodejs_version: "6.4.0"   # same results as 6.0, 6.1, 6.2, 6.3
