sudo: false
language: node_js
node_js:
  - stable
  - 6
script: 
  - npm test
matrix:
  fast_finish: true
branches:
  only:
  - master
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
after_success:
  - npm run report-coverage