os:
  - linux
  - osx
sudo: false
branches:
  only:
    - master
    - develop
language: node_js
script: 
  - npm test
cache:
  directories:
    - node_modules
node_js:  # Test only current versions of NodeJS >= 8.0 (Mid 2017) to reduce server loads
  - stable
  - "9.4.0"   # same results as 9.0.x, 9.1.x, 9.2.x, 9.3.x
  - "8.9.4"   # same results as 8.7.x, 8.8.x, 8.9.x
  - "8.6.0"   # same results as 8.3.x, 8.4.x, 8.5.x
  - "8.2.1"   # same results as 8.0.x, 8.1.x, 8.2.x
  # - "7.10.1"  # same results as 7.6.x, 7.7.x, 7.8.x, 7.9.x, 7.10.x
  # - "7.5.0"   # same results as 7.1.x, 7.2.x, 7.3.x, 7.4.x
  # - "6.12.3"  # same results as 6.5.x, 6.6.x, 6.7.x, 6.8.x, 6.9.x, 6.10.x, 6.11.x, 6.12.x
  # - "6.4.0"   # same results as 6.0.x, 6.1.x, 6.2.x, 6.3.x
matrix:
  fast_finish: true
  include:  # Test additional versions in Matrix NodeJS < 8.0 && >= 6.0
    - node_js: "node"
      env: PRETEST=true
    # - node_js: "9.3.0" # same results as 9.0.x, 9.1.x, 9.2.x, 9.3.x
    #   env: TEST=true ALLOW_FAILURE=true
    # - node_js: "8.9.4" # same results as 8.7.x, 8.8.x, 8.9.x
    #   env: TEST=true ALLOW_FAILURE=true
    # - node_js: "8.6.0" # same results as 8.3.x, 8.4.x, 8.5.x
    #   env: TEST=true ALLOW_FAILURE=true
    # - node_js: "8.2.1" # same results as 8.0.x, 8.1.x, 8.2.x
    #   env: TEST=true ALLOW_FAILURE=true
    - node_js: "7.10.1" # same results as 7.6.x, 7.7.x, 7.8.x, 7.9.x, 7.10.x
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "7.5.0" # same results as 7.1.x, 7.2.x, 7.3.x, 7.4.x
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.12.3" # same results as 6.5.x, 6.6.x, 6.7.x, 6.8.x, 6.9.x, 6.10.x, 6.11.x, 6.12.x
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.4.0" # same results as 6.0.x, 6.1.x, 6.2.x, 6.3.x
      env: TEST=true ALLOW_FAILURE=true
after_success:
  # - npm run report-coverage